preprocessing:
  remove_punctuation: True
  remove_digits: False
  remove_stopwords: False

data:
  test_size: 0.15
  val_size: 0.15
  random_state: 42
  sample_size: 120000  # Added for data sampling

model:
  name: 'sentence-transformers/all-MiniLM-L6-v2'
  num_labels: 4

training:
  batch_size: 16
  epochs: 75
  learning_rate: 1e-1
  reduction_factor: 0.1
  patience: 2

evaluation:
  use_test_data: True
